# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/go-mitmproxy/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
archives:
  - replacements:
      darwin: macosx
      linux: linux
      windows: windows
      386: x86
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
